[features]
seeds = false
skip-lint = false
[programs.localnet]
houses_stake = "Ezy2MxpDoPvaRB7fPq32vgFXiZHcKsX3TEd7d7WFPFm7"
houses_token_keeper = "7T3CM2YhJMRQyVRCqY2ShaZydzHCCDBZUTyXzXGnJ3Wh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/aleksandrtirik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
