[features]
seeds = false
skip-lint = false
[programs.localnet]
houses = "jS6eJdA62z3CGBGseehYVPpYdrRbzd5rdFjw3ZGjg3F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aleksandrtirik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
