[features]
seeds = false
skip-lint = false
[programs.localnet]
houses_stake = "3A6KoMNEqphcqdLJvifU2dxWxbkQVpFWZgRCjGGpt776"
houses_token_keeper = "BnHCabsYvwUPEkd22RMbk2y5g8XSgbhU435yGVik12vc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aleksandrtirik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
