[features]
seeds = false
skip-lint = false
[programs.localnet]
houses_stake = "GBcstHFNnGBqBpiZfurPDZJoousWxYZBfUyAipYbRUXc"
houses_token_keeper = "2bgCfBD4DQKQHNrtRhHMTYisiGyRchvHZGH96iqb7F9x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/aleksandrtirik/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
